### ISSUE TITLE
uploaded file path is not correct

### ISSUE THREAD

**Issue by rajasimon** [ckopanos/django-google-cloud-storage#2]
I searched lot about how to upload files to google appengine. I found your 'django-google-cloud-storage' seems good to me. 

What i did is .

Download your `googleCloud.py` file and place it in `root folder` then

`settings.py` file 

> GOOGLE_CLOUD_STORAGE_BUCKET = '/bucket' 
> GOOGLE_CLOUD_STORAGE_URL = 'http://storage.googleapis.com/bucket_me' 
> GOOGLE_CLOUD_STORAGE_DEFAULT_CACHE_CONTROL = 'public, max-age: 7200'
> 
> DEFAULT_FILE_STORAGE = "googleCloud.GoogleCloudStorage"'

That's all right ?

Then if i am gonna upload one file then actually file path is 

> http://localhost:8000/blobstore/blob/AMIfv97xNuEPzR5RzG_G1MbZ5_PWPksPCk4YhoagDRXZ5eP63rU7tf4VK2_FqEsIS_rbyTge8z0EfaHXL3FJq56UA7AbQQ6dayIJFiZ71i6KEb4U8tWXAgdHWTpw3ulMEOzl-NvBcy_N9Y4Wt2avGT7MSvTmT-bTYQbAropWdiPoJ3N2orhTqyfqtO__o7y_JgrDUPt12xZW?display=inline

And why what's happening here .!

**Comment by ckopanos** [comment]
Actually the path you mention is this when you test your app locally having
DEBUG = True in your settings.py

When you deploy your app the file path will be like
storage.google..../bucket/your path/your file..

Christos Kopanos
RedMob Applications
www.RedMob.gr
www.RedMob.eu
+30 2431 100 302

Στις 28 Οκτ 2014 1:37 μ.μ., ο χρήστης "Simon Rajasingh" <
notifications@github.com> έγραψε:

**Comment by rajasimon** [comment]
oh ..wow .. I didn't know that .. Thanks for the quick reply + `star` for you

**Comment by geojacobm6** [comment]
Same issue;In locally it is working fine.
But when I uploaded the codes to server, i am getting same url like http://localhost:8000/blobstore/blob/PWPksPCk4YhoagDRXZ5eP63rU7tf4VK2_FqEsIS_rbyTge8z0EfaHXL3FJq56UA7AbQQ6dayIJFiZ71i6KEb4U8tWXAgdHWTpw3ulMEOzl-NvBcy_N9Y4Wt2avGT7MSvTmT-bTYQbAropWdiPoJ3N2orhTqyfqtO__o7y_JgrDUPt12xZWAMIfv97xNuEPzR5RzG_G1MbZ5?display=inline


Whether i have to make any changes in settings.py file while deploying to server?
