### ISSUE TITLE
support with Google Compute Engine

### ISSUE THREAD

**Issue by rajasimon** [ckopanos/django-google-cloud-storage#3]
Hi .. 

Is this best suited with Google Compute Engine .?

I followed exactly same procedure but i am gettting below error 

> No module named google.appengine.api.blobstore

If i am remove the line from googleCloud.py then the result is ..

> No module named cloudstorage

There is no need for `Google App Engine` here ? right ?

How to fix this ?

**Comment by ckopanos** [comment]
It cannot work with compute engine, at least at first sight.

The storage needs some specific app engine libraries, and was made for appengine integration.
I have not tested it with compute engine, it might work, though i am not sure how authentication with google cloud storage would take place, it might need to be implemented. With app engine authentication with cloud storage (your own buckets, or buckets where you have read / write permissions i suppose) is is not a problem.

If you try by removing the import linem be sure to also change line 89.. def url(...

with

```
def url(self, name):
    return self.base_url+"/"+name
```

this is where create_gs_key function is used.. and removing the import causes the second error.

I have not tested it, if it works, let me know...

**Comment by rajasimon** [comment]
Error : in `open` function `gcs` undefined. 

I'm in the urgent to give the test link to my organization so i just drop this idea. I ll check this later and let you know ..! 

Thanks

**Comment by ckopanos** [comment]
It wont work probably with compute engine. The gcs client library is an app engine library... so the solution will need more modifications to work with a vm machine in compute engine..
